import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import { Button,User,Grid } from '@nextui-org/react';


export default function Home() {

  const {data:session}=useSession()

if (session) {
  return (
    <Grid.Container  alignContent="center" gap={1} justify="center" style={{height:550}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="png" href="/favicon.png" />
      </Head>
      <User
      src={session.user.image}
      name={session.user.name}
      description={session.user.email}/>
      <Button onClick={()=>signOut()}>signOut</Button>
    </Grid.Container>
  )
}else{
  return(
    
    <Grid.Container  direction="column"  alignContent="center" gap={1} justify="center" style={{height:550}} >
      
         <Grid>   
                   <Button onClick={()=>signIn()}>signIn</Button>
                   ------------------------------
                   <Button  >signUp</Button>
         </Grid>
    </Grid.Container>
  )
}
}

