import React,{useMemo} from "react";
import Head from 'next/head'
import { useSession, signIn, signOut } from "next-auth/react"
import { Button,User,Grid,Input,useInput,Container } from '@nextui-org/react';
export default function Home() {
  
  const {data:session}=useSession()
  const { value, reset, bindings } = useInput("");

  const validateEmail = (value) => {
    return value.match(/^[A-Z0-9._-]+@[A-Z]+.[com]{3}$/i)}

  const helper = useMemo(() => {

    if (!value)
      return {
        text: "",
        color: "",};
        
    const isValid = validateEmail(value);
    return {
      text: isValid ? "Correct email" : "Enter a valid email",
      color: isValid ? "success" : "error",};

  }, [value]);

if (session) {
  return (
    <Grid.Container  alignContent="center" gap={1} justify="center" style={{height:550}}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="png" href="/favicon.png" />
      </Head>

      <>

      <User
      src={session.user.image}
      name={session.user.name}
      description={session.user.email}/>

      <Button onClick={()=>signOut()}>signOut</Button>
      </>

    </Grid.Container>
  )
}else{
  return(
    
    <Grid.Container  direction="column"  alignContent="center" gap={1} justify="center" style={{height:550}} >
         <Grid > <h1>LogIn</h1></Grid>
         <Grid> 
                <form >
         <Grid>
                <Input
                     {...bindings}
                     clearable
                     shadow={false}
                     onClearClick={reset}
                     status={helper.color}
                     color={helper.color}
                     helperColor={helper.color}
                     helperText={helper.text}
                     type="email"
                     label="Email"
                     placeholder="Enter your Email"/>
         </Grid>
         <Grid>
               <Input
                 clearable
                 type="password"
                 label="password"
                 placeholder="password"/>
         </Grid>
         <Grid>
                   <Button>LogIn</Button>
         </Grid>
         <Grid>   
                   <Button onClick={()=>signIn()}>signIn</Button>
         </Grid>
               </form>
         </Grid>

    </Grid.Container>
  )
}
}
